apiVersion: apps/v1
kind: Deployment
metadata:
  name: career-page-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: career-page
  template:
    metadata:
      labels:
        app: career-page
    spec:
      containers:
      - name: career-page-container
        image: gcr.io/terraform-poc-410807/Career-Page.git:latest
        ports:
        - containerPort: 8888