# Generated by Django 3.1.3 on 2021-03-21 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=500)),
                ('jobType', models.CharField(max_length=500)),
                ('openings', models.IntegerField()),
                ('experiences', models.CharField(max_length=500)),
                ('educationLevel', models.CharField(max_length=500, null=True)),
                ('description', models.CharField(max_length=6000)),
                ('requirements', models.TextField(max_length=6000)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mob', models.CharField(max_length=10)),
                ('mailID', models.CharField(max_length=50)),
                ('resume', models.FileField(upload_to='resume/')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrer.jobs')),
            ],
        ),
    ]
